### ISSUE TITLE
Optimize Vector Sizes

### ISSUE THREAD

**Issue by octopusCat88** [nagam11/PP2#1]
## Task
- [x]  provide and choose several (N) vector sizes
- [x]  extract features via biovec for each of the N vector sizes
- [x]  train model with cross-validation
- [x]  plot different metrics
- [x]  analyse and explain results

## Plotting
- [x] define input format
- [x]  training vs. validation metrics
- [x] validation metrics across different vector sizes
